- name: Install MYSQL DB
  apt:  
    name: ['mysql-server','mysql-client'] 
    state: present 

- name: Copy mysqld conf
  copy: src=templates/mysqld.cnf  dest=/etc/mysql/mysql.conf.d



- name: start mysql service
  service:
    name: mysql
    state:  started
    enabled:  yes

- name: Create App DB
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"
    state: present 

- name: Create DB User
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_user}}"
    password: "{{ db_user_password }}"
    priv: '*.*:ALL'
    state:  present
    host: '%'